### ISSUE TITLE
Głowy członków gildii

### ISSUE THREAD

**Issue by Selcouth** [SlimaKCoder/projectQ#11]
Po wybraniu gildii wyświetlają się ich głowy, gdy po najechaniu wyświetla się tylko taki malutki napis, zrób to w tooltip będzie wyglądało estetyczniej :+1:

**Comment by SlimaKCoder** [comment]
Ewentualnie mogę zwiększyć wielkość napisu po najechaniu na głowę. Dodawanie "tooltip" jako takiego wymagało by JavaScript. Nie ma sensu dodawać takiej kobyły jaką jest JS do projektu dla tak błahej rzeczy....

**Comment by SlimaKCoder** [comment]
Dodałem coś wyglądającego jak "tooltip", ale działającego przy pomocy CSS i współpracującego z motywami, które już są dodane. Ponad to poprawiłem wszystkie zapytania MySQL dla pluginy FunnyGuilds. Polecam byś przetestował najnowszą wersję.

Commit: https://github.com/SlimaKCoder/projectQ/commit/437966ae6161ddaa7921d29c9efac6c307879011
Pobieranie: https://github.com/SlimaKCoder/projectQ/archive/Development.zip
