### ISSUE TITLE
Używanie label w nazwie gildii zamiast nawiasów

### ISSUE THREAD

**Issue by TheMolkaPL** [SlimaKCoder/projectQ#8]
Obecnie projectQ wyświetla gildie w wyglądzie `[GILDIA]`
Moim zdaniem lepszym rozwiązaniem będzie użycie label z Bootstrap ([dokumentacja oraz demonstracja](http://getbootstrap.com/components/#labels)).

```html
<span class="label label-default">GILDIA</span>
```

Kolor label można dostosować do koloru tabeli w której się znajduje.

**Comment by SlimaKCoder** [comment]
Myślę, że nie będę tego wdrążał. "Label" zmniejsza czcionkę i przesuwa tekst ku górze (coś jak indeks górny). W teorii mógłbym zdefiniować dodatkowe CSSy dla "label", ale kłóciło by się to z założeniem, że wszystko ma być kompatybilne z Boostrap'em.
